### ISSUE TITLE
Coomatrix compare

### ISSUE THREAD

**Issue by losanc** [Andlon/matrixcompare#9]
Hi,

when I trying to compare a coomatrix, with another matrix. And it gives the error `DuplicateSparseEntry`, but I think duplicate entries are kind of allowed in coomatrix.

**Comment by Andlon** [comment]
This is a deliberate decision, although it can be debated whether it's the right one. `matrixcompare` tries to be general and not assume too much about the matrices that are used. In general, if a matrix format has duplicate entries, it is not clear to `matrixcompare` what this means. Yes, they *could* be summed together, which is what is done when converting a `CooMatrix` to `CsrMatrix` in `nalgebra-sparse`, for example. However, this is not necessarily desirable for other formats and/or libraries.

There is also the risk that the reason for duplicate entries is due to a bug in the format, not a conscious decision. `matrixcompare` is intended to offer a reliable way of testing *new* matrix formats, so we'd rather like to detect this case.

Therefore, if the user wants to compare matrices with duplicate entries, they need to either:
- decide what to do with duplicate entries: for example, sum them up,
- or convert them into a format which does not have duplicate entries

For `nalgebra-sparse`, you could for example convert the `CooMatrix` to `CsrMatrix` first before comparing.

**Comment by losanc** [comment]
Ok. Thanks for the explanation!
